[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && echo 'Backend build complete'"]

[start]
cmd = "cd backend && node server.js"
